### ISSUE TITLE
twitch bot chat listener for responding to pet inquiries

### ISSUE THREAD

**Issue by jibranabsarulislam** [alveusgg/extension#106]
hi all, i think i'm opening an issue in the wrong place as this is for the extension and not necessarily bot commands. please let me know if I need to relocate this issue

today's Monkey Move-In had some viewers inquiring how to get ambassadors as pets, which had Maya re-explain frequently and have chat spam !notapet 

would it be viable for the twitch bot to check each message's language pattern for an inquiry and respond to it with the !notapet text? 
although, i would think this would affect interactivity, troll frequency, and viewers trying to trigger it with edge case language patterns

**Comment by MattIPv4** [comment]
I think a Twitch bot that responds to messages is probably out of scope for this repository, as it is just an extension. It does not have an ability to respond to messages.

**Comment by jibranabsarulislam** [comment]
got it, thanks for your quick response Matt
