### ISSUE TITLE
Conservation tooltip does not fit mobile panel

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/extension#115]
Maybe we can open it to the bottom and align right.

![image](https://github.com/alveusgg/extension/assets/684458/2161c38d-ac24-42bf-b402-e476051ca7a4)

**Comment by MattIPv4** [comment]
We probably need a bit of JS logic in there that assesses whether it will fit to the right or not, and switch it to top-aligned if not.

**Comment by t3st1n9** [comment]
Hi, could i get assigned this issue? I'd like to give it a try.

**Comment by MattIPv4** [comment]
Sure :)
