### ISSUE TITLE
[Idea]: Port extension to a truffle app

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/extension#148]
It would be nice to have the extension on youtube as well. Youtube does not offer a way to add custom extensions. Instead we could offer an app on truffle: https://docs.truffle.vip/truffle-embeds/what-are-truffle-apps

As far as I understand it, this could either be an app in the sidebar or embedded on the stream page. A video overlay like it is possible on twitch is not possible with truffle. The implementation would probably look a lot like the panel view/mobile view of the current extension.

Triggering Popups can either be omitted, or another solution has to be found, since commands will probably still be sent in twitch chat and youtube does not offer a chat api anyways. It might be possible to scrape the chat, but thats probably not worth the effort.

**Comment by MattIPv4** [comment]
Closing as I don't think this would be worth the effort, and Truffle does not support player overlays.
