### ISSUE TITLE
Replace SCSS modules with Tailwind

### ISSUE THREAD

**Issue by abdullahmorrison** [alveusgg/extension#15]
To have a more consistent tech stack across the AlveusGG projects, look to replace the SCSS modules usage here with Tailwind.

Reference the tailwind config in https://github.com/alveusgg/alveusgg/blob/main/apps/website/tailwind.config.ts, and perhaps think about how we could even abstract that into a shared package (like alveusgg/data), so our theme is consistent.

**Comment by abdullahmorrison** [comment]
Start using mixins for repeated code blocks

**Comment by abdullahmorrison** [comment]
change @import to @use

**Comment by silaselisha** [comment]
@MattIPv4 I would like to work on this issues.

**Comment by MattIPv4** [comment]
Sure, go for it. I recommend referencing the tailwind config in https://github.com/alveusgg/alveusgg/blob/main/apps/website/tailwind.config.ts, and perhaps think about how we could even abstract that into a shared package (like alveusgg/data), so our theme is consistent.

**Comment by mahenoorsalat** [comment]
Hello @MattIPv4 can I contribute to this project .. As I have strong foundation in front-End Technologies and design ..

I will work in this continuously.. Hope you can assign me this issue 

Thank You :)

**Comment by MattIPv4** [comment]
Go for it 👍 I recommend perhaps splitting this into multiple PRs, migrating one bit to Tailwind at a time, so its not one massive PR at the end that will take ages to review and risks merge conflicts.

**Comment by MattIPv4** [comment]
👋 @mahenoorsalat any update on this? I'd like to let someone else work on this if you're not planning to get a PR opened soon.

**Comment by mahenoorsalat** [comment]
Oh sorry I didnot see this early ! let me work on this ! Thank You :)

**Comment by MattIPv4** [comment]
👋 @mahenoorsalat just checking in again to see how things are going?
