### ISSUE TITLE
Add tool tips (CSS only)

### ISSUE THREAD

**Issue by abdullahmorrison** [alveusgg/extension#25]
Tooltips will pop up on hover.
- [ ] One next to activation buttons 

<img src="https://user-images.githubusercontent.com/49528805/213881529-2cae4fbe-aafa-4ec2-8d40-2fe383598468.png" width=300/>

- [ ] One inside an ambassador card, next to the IUCN status that explains what an IUCN status is 

<img src="https://user-images.githubusercontent.com/49528805/213882521-0d64dcf5-85ae-4a1e-99a0-fc10cd189160.png" width = 500/>

**Comment by GersonMJL** [comment]
Yo, I'll try to implement this

**Comment by ThatGravyBoat** [comment]
As a temporary change for the buttons at least the [`title` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) would be excellent while tooltips are being developed.

**Comment by MushkyQT** [comment]
@GersonMJL Hey, are you still planning on implementing the tooltips? If not just lmk, I'll have a go

**Comment by GersonMJL** [comment]
@MushkyQT Yeah you can have it, I don't have the time rn :/

**Comment by MushkyQT** [comment]
@GersonMJL Sounds good!

**Comment by MattIPv4** [comment]
👋 @MushkyQT Any progress on this, or should I unassign it so someone else can take a look?

**Comment by jibranabsarulislam** [comment]
^Please let me know the status, I'd be down to take a look!

**Comment by MattIPv4** [comment]
Sure, I'll re-assign this to you :)

**Comment by MattIPv4** [comment]
#101
