### ISSUE TITLE
How to help species button

### ISSUE THREAD

**Issue by abdullahmorrison** [alveusgg/extension#58]
Add a button under an ambassador's card that flips the card and shows a list of points about how one can help that ambassador's species.

**Comment by abdullahmorrison** [comment]
- [ ] Make sure to check that it doesn't effect the birthday hat functionality

**Comment by abdullahmorrison** [comment]
This is in the branch amorrison/help-species. It was set up before the data changes were made. 

This doc is the information that I got from all the animal quests' recommendation section before winnie:
[AlveusCallToActions.docx](https://github.com/alveusgg/extension/files/11524711/AlveusCallToActions.docx)

The explantion and notes parts of the doc were rejected by maya because they were not strong enough and she does not have time to fix them. I think it's important be able to explain the "why" for each point but if maya can't approve it then just having the points without an explaination is better than nothing.

**Comment by jibranabsarulislam** [comment]
if i reach approval on #25 and get a PR open for #80, i'd be happy to implement this! (continuing the work off of your branch[?])

would you have any suggestions for storing the data or would a JSON be sufficient?

**Comment by MattIPv4** [comment]
My gut says this honestly might be making the extension too complex and information-sense.

With the cards now linking to the site, it would probably make sense to have this information on the site rather than the extension?

If you're interested in working on that, feel free to open an issue there and we can discuss it more :)

**Comment by jibranabsarulislam** [comment]
got it, yeah that make sense. thanks again @MattIPv4!
should I open that issue on the https://github.com/alveusgg/alveusgg repo?

**Comment by MattIPv4** [comment]
Yeah, that'd be great, so we can discuss where it'd fit on the site best.

**Comment by MattIPv4** [comment]
Closing in favour of https://github.com/alveusgg/alveusgg/issues/289
