### ISSUE TITLE
Hide cursor on idle

### ISSUE THREAD

**Issue by abdullahmorrison** [alveusgg/extension#80]
make the cursor disappear while on the overlay and idle so it doesn't block the video

**Comment by SUSINDRAREDDY** [comment]
Hey I like your project, I like to contribute in this issue. 
Is it up for grabs?

**Comment by abdullahmorrison** [comment]
Go ahead, I'll assign it to you

**Comment by SUSINDRAREDDY** [comment]
Can you provide me more details to address this issue

![image](https://github.com/alveusgg/extension/assets/126981466/607e9f69-868f-47a0-9b6c-5741df742216)
 Is this issue for full screen?

**Comment by MattIPv4** [comment]
👋 Hey @SUSINDRAREDDY, have you had a chance to get started on this? Anything we can do to help?

**Comment by MattIPv4** [comment]
No movement, unassigning so someone else can take a look at tackling this if they wish.

**Comment by jibranabsarulislam** [comment]
hey all, I've got this one working on my branch. with your permission I'll open a PR w more info

**Comment by MattIPv4** [comment]
Sure 👍

**Comment by MattIPv4** [comment]
#102
